spring.application.name=examination

server.port=8080

robot.mqtt.broker=tcp://192.168.7.27:1883
robot.mqtt.client-id=leader-sub

robot.mqtt.leader.pos-topic=leader/pos
robot.mqtt.leader.vels-topic=leader/vels
robot.mqtt.leader.state-topic=leader/state

robot.mqtt.follower.pos-topic=follower/pos
robot.mqtt.follower.vels-topic=follower/vels
robot.mqtt.follower.state-topic=follower/state