spring.application.name=examination

server.port=8080

robot.mqtt.broker=tcp://localhost:1883
robot.mqtt.client-id=leader-sub
robot.mqtt.pos-topic=leader/pos
robot.mqtt.vels-topic=leader/vels
robot.mqtt.state-topic=leader/state